name: Quick Tests

on:
  push:
    branches: [ dev_clean_up, feature/* ]
  pull_request:
    branches: [ dev_clean_up ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install pytest

    - name: Run core tests only
      run: |
        pytest tests/test_constants.py tests/test_helper_functions.py tests/test_core_adaptfx.py -v --tb=short --maxfail=3

    - name: Quick smoke test
      run: |
        python -c "
        from adaptive_fractionation_overlap.core_adaptfx import adaptfx_full
        import numpy as np
        
        # Quick smoke test
        volumes = [0.0, 1.0, 2.0, 1.5, 2.5, 1.8]
        result = adaptfx_full(volumes)
        assert len(result) == 3, 'Should return 3 values'
        assert len(result[0]) == 5, 'Should have 5 doses'
        assert all(6.0 <= dose <= 10.0 for dose in result[0]), 'Doses should be in bounds'
        print('✅ Smoke test passed!')
        "